import "../globals.css";
import type { Metadata } from "next";
import UserPageHeader from "./components/UserPageHeader";
import UserPageSideBar from "./components/UserPageSideBar";

import { siteConfig } from "@/lib/site";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Dashboard | Church Finder PH",
  description: "Generated by create next app",
};

export default function UserPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(siteConfig.font.sans.className, "flex bg-muted dark")}
      >
        <UserPageSideBar />
        <div className='pl-[240px] flex-1'>
          <UserPageHeader />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
