import "../globals.css";
import type { Metadata } from "next";
import UserPageHeader from "./components/UserPageHeader";
import UserPageSideBar from "./components/UserPageSideBar";

import SessionProvider from "@/providers/SessionProvider";

import { siteConfig } from "@/lib/site";
import { cn } from "@/lib/utils";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Dashboard | Church Finder PH",
  description: "Generated by create next app",
};

export default async function UserPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  if (!session || !session.user) {
    return redirect("/signin");
  }

  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(siteConfig.font.sans.className, "flex bg-muted dark")}
      >
        <SessionProvider session={session}>
          <UserPageSideBar />
          <div className='pl-[240px] flex-1'>
            <UserPageHeader />
            <main>{children}</main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
